feature/card
castromaciel/ui-rollingcode pull request #8
Opened 2023-02-13 02:47 UTC by castromaciel

- Add basic carde modes
- Add tests
- Export files

2023-02-13 03:35 UTC, Nidev-lab commented
Add a screenshoot for each pr, please.

2023-02-13 03:52 UTC, castromaciel commented
# Card 

### mode:  classic (default)

```tsx
<Card
  title="Classic"
  buttonRight="View more"
  onClickRight={() => console.log('Clicked')}
  description="Lorem ipsum dolor sit amet, adipiscing elit."
  image="https://picsum.photos/id/237/300/300"
  altImage="Alternative text"
/>
```

<img width="350" alt="image" src="https://user-images.githubusercontent.com/83432755/218366385-93fc4583-2e32-4261-965d-6eb77c34ee5e.png">

### mode: product

```tsx
<Card
  mode="product"
  title="Product"
  price="1,034.50"
  buttonRight="Buy"
  onClickRight={() => console.log('Clicked')}
  description="Lorem ipsum dolor sit amet, consectetur adipiscing elit."
  image="https://picsum.photos/id/27/2000/2000"
  altImage="Alternative text"
/>
```

<img width="357" alt="image" src="https://user-images.githubusercontent.com/83432755/218366530-cf8708b9-8bbf-491c-8258-2eefb3dede1b.png">

2023-02-14 03:56 UTC, Nidev-lab requested changes

2023-02-14 03:59 UTC, castromaciel commented on src/typinigs.d.ts
> +}
Solved at commit: [fix in the end line at typings file](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/2a0c68d0e739acfb2421ab75b4b00e808455d4e2)

2023-02-14 04:11 UTC, castromaciel commented on src/structure/Card/Card.test.tsx
> +/* eslint-disable no-undef */
That was i've got the following error

```
'describe' is not defined. eslint (no-undef)
```

I've solved adding

``` json
"env": {
    "jest": true
}
```

 at `.eslintrc.json`

Associate commit: [fix eslint-disable no-undef for tests with jests](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/2f8e1116809d707bdca107b962b4937ab7c6ade4)

2023-02-14 04:12 UTC, castromaciel commented on src/structure/Card/card.module.scss
> +
Solved at commit '[fix end line at styles](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/74f9576b4646807204b3bb644306e035048f7bb1)'

2023-02-14 04:12 UTC, castromaciel commented on src/structure/Card/card.module.scss
> +    }
Solved at commit '[fix end line at styles](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/74f9576b4646807204b3bb644306e035048f7bb1)'

2023-02-14 18:41 UTC, castromaciel commented on src/structure/Card/Card.tsx
> +                : null }
Change at commit: [Add default props](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/0a217b9400799f8781c778fb3cd7643900356421) and [fix validate at button left and colors](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/19cbe8bb872f62839e7c10804012dcccabf75688)

It was my fault, i've confused by [this](https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx). But in our case, we don't compare anything with `0` or `''`.

2023-02-14 18:41 UTC, castromaciel commented on src/structure/Card/Card.tsx
> +  price = 100,
Solved at commit [Add default props](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/0a217b9400799f8781c778fb3cd7643900356421)

2023-02-14 18:43 UTC, castromaciel commented on src/structure/Card/card.module.scss
> +        border: 1px solid #C82526;
Okey, i'll be working at that ticket, and when it's finished, I'll make this changes.

Applies at commit: [fix validate at button left and colors](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/19cbe8bb872f62839e7c10804012dcccabf75688)

2023-02-14 18:48 UTC, castromaciel commented on src/structure/Card/Card.tsx
> +  buttonLeft?: string
Solved at [Add default props](https://github.com/castromaciel/ui-rollingcode/pull/8/commits/0a217b9400799f8781c778fb3cd7643900356421).

More than `action` property, I still `onClick`. That's beacause, the action button we define is MouseEventHandler `onClick`

2023-02-14 20:13 UTC, Nidev-lab approved these changes

2023-02-14 20:41 UTC, merged

2023-02-14 20:44 UTC, castromaciel commented
:tada: This PR is included in version 0.1.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/ui-rc-components/v/0.1.0)
- [GitHub release](https://github.com/castromaciel/ui-rollingcode/releases/tag/v0.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: